### ISSUE TITLE
ss01 doesn't work InDesign

### ISSUE THREAD

**Issue by Tarobish** [Tarobish/Katibeh#86]
Still we don't have style, i just changed the language to check the ligatures

**Comment by graphicore** [comment]
The laguages work in Firefox and Chrome as far as I can tell. Where do you test, what is your input, what do you expect and what do you get?

**Comment by Tarobish** [comment]
Here it works too, but if you remember it was suppose to be a style
when I’m changing the language from Persian to the arabic it works but i don’t have any option to  have ligatures without changing the Language
Sometimes even in Persian, we use ligatures.

**Comment by graphicore** [comment]
Did you try to turn on "dlig"

**Comment by Tarobish** [comment]
Yes, its on

**Comment by graphicore** [comment]
well, that works in the browsers :-/

**Comment by Tarobish** [comment]
:(

**Comment by graphicore** [comment]
can you try it again?

**Comment by graphicore** [comment]
This is about `ss01` in InDesign. Which seems broken, but I have no Idea how to fix it. The `ss01` feature in itself is seemingly simple and we even uses makeotf of the AFDKO, so that thing should know how to make features that work in Adobe-InDesign.

It works in the (Harfbuzz-?) browsers, as documented in #66.

I'll mark this with **wontfix** until new insights come up.
